---

- name: Get all Route53 hosted zones
  route53_info:
    query: hosted_zone
    max_items: 500
  register: r_route53_hosted_zones

- debug:
    var: route53_default_hosted_zone_name

- name: Capture the hosted zone
  set_fact:
    route53_hosted_zone: "{{ r_route53_hosted_zones | json_query(query) | first | default(omit) }}"
  vars:
    query: HostedZones[?Name==`{{ route53_default_hosted_zone_name }}`]

- name: Fail if Route53 hosted zone doesn't exist
  fail:
    msg: |-
      You must create a Route53 public hosted zone named

      {{ cluster_name }}.{{ base_domain }}

      If you want to use a different hosted zone that contains a subset of the
      domain above, you can alternatively define "route53_hosted_zone_id" in
      your variables file.
  when: route53_hosted_zone is undefined

- name: Set the hosted zone ID
  set_fact:
    route53_hosted_zone_id: "{{ route53_hosted_zone.Id | replace('/hostedzone/', '') }}"
