#!/usr/bin/env python3

from deploy.cli import OpenShiftDeployCLI
from deploy.deploy import SUPPORTED_CONTAINER_RUNTIMES, OpenShiftDeploy
from deploy.helper import BASE_DIR, ContainerRuntimeMissingError


if __name__ == '__main__':
    cli = OpenShiftDeployCLI()
    known_args, extra_args = cli.parse_known_args()

    try:
        od = OpenShiftDeploy(
            skip_update=known_args.skip_update,
        )
    except ContainerRuntimeMissingError:
        print('\n'.join([
            'You do not have a supported container runtime installed.',
            '',
            'This script supports the following container runtimes:',
            '\n'.join('  - {}'.format(i) for i in SUPPORTED_CONTAINER_RUNTIMES),
            '',
            'Please install one of those options and try again.'
        ]))

    if known_args.action == 'shell':
        od.shell()
    elif known_args.action == 'create':
        od.create(known_args.vars_file, extra_args)
    elif known_args.action == 'destroy':
        od.destroy(known_args.vars_file, extra_args)
    elif known_args.action == 'start':
        od.start(known_args.vars_file, extra_args)
    elif known_args.action == 'stop':
        od.stop(known_args.vars_file, extra_args)
    elif known_args.action == 'info':
        od.info(known_args.vars_file, extra_args)
    elif known_args.action == 'ssh':
        od.ssh(known_args.vars_file)
